import bcrypt from 'bcryptjs';

const dummyData = {
  users: [
    {
      name: 'Hamza',
      email: 'admin@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
      isSeller: true,
      seller: {
        name: 'Puma',
        logo: '/images/logo1.png',
        description: 'best seller',
        rating: 4.5,
        numReviews: 120,
      },
    },
    {
      name: 'Talha',
      email: 'user@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Nike Slim Shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 30,
      countInStock: 13,
      brand: 'Bonanza',
      rating: 3.5,
      numReviews: 20,
      description: 'high quality product',
    },
    {
      name: 'Adidas Fit Shirt',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 70,
      countInStock: 8,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 13,
      description: 'high quality product',
    },
    {
      name: 'Lacoste Free Shirt',
      category: 'Shirts',
      image: '/images/p3.jpg',
      price: 110,
      countInStock: 5,
      brand: 'Khadi',
      rating: 4.0,
      numReviews: 17,
      description: 'high quality product',
    },
    {
      name: 'Nike Slim Pant',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 50,
      countInStock: 0,
      brand: 'Levis',
      rating: 2,
      numReviews: 6,
      description: 'high quality product',
    },
    {
      name: 'Puma Slim Pant',
      category: 'Pants',
      image: '/images/p5.jpg',
      price: 95,
      countInStock: 16,
      brand: 'Lee',
      rating: 1.5,
      numReviews: 9,
      description: 'high quality product',
    },
    {
      name: 'Adidas Fit Pant',
      category: 'Pants',
      image: '/images/p6.jpg',
      price: 35,
      countInStock: 3,
      brand: 'Turbo',
      rating: 1.0,
      numReviews: 5,
      description: 'high quality product',
    },
  ],
};
export default dummyData;
