export const SHOPPING_CART_ADD_ITEM = 'SHOPPING_CART_ADD_ITEM';
export const SHOPPING_CART_ADD_ITEM_FAIL = 'SHOPPING_CART_ADD_ITEM_FAIL';
export const SHOPPING_CART_REMOVE_ITEM = 'SHOPPING_CART_REMOVE_ITEM';
export const SHOPPING_CART_SAVE_SHIPPING_ADDRESS =
  'SHOPPING_CART_SAVE_SHIPPING_ADDRESS';
export const SHOPPING_CART_SAVE_PAYMENT_METHOD =
  'SHOPPING_CART_SAVE_PAYMENT_METHOD';
export const SHOPPING_CART_EMPTY = 'SHOPPING_CART_EMPTY';
